import type { Metadata } from "next";
/* eslint-disable @next/next/no-img-element -- mídia publicada pelo painel já é otimizada no envio */
import { getPublicContent } from "../../lib/site-content";
export const metadata: Metadata = {
  title: "Devocionais",
  description: "Leia devocionais e reflexões bíblicas publicados pela PIBRG para a caminhada da semana.",
  alternates: { canonical: "/devocionais" },
};
export const dynamic = "force-dynamic";
export default async function DevocionaisPage() { const devotionals=await getPublicContent("devotional"); const featured=devotionals[0]; const previous=devotionals.slice(1); return <main><section className="page-hero devotional-hero"><div className="devotional-hero-image" aria-hidden="true" /><div className="container page-hero-inner"><p className="eyebrow eyebrow-light">Devocionais</p><h1>Um momento de pausa.<br />Uma palavra para a semana.</h1><p>Reflexões breves para aproximar a Palavra da vida cotidiana.</p></div></section>{featured && <section className="section devotional-feature"><div className="container devotional-feature-grid">{featured.imageUrl ? <img className="devotional-photo devotional-photo-real" src={featured.imageUrl} alt={`Imagem do devocional ${featured.title}`} style={{ objectPosition: featured.imagePosition }} /> : <div className="devotional-photo" role="img" aria-label="Bíblia aberta sobre uma mesa iluminada pela manhã" />}<article><p className="eyebrow">Devocional em destaque • {formatDate(featured.date)}</p><h2>{featured.title}</h2><p className="scripture">Palavra para esta semana <strong>{featured.subtitle}</strong></p>{featured.author && <p className="devotional-author">Por {featured.author}</p>}<p>{featured.body}</p><div className="devotional-prayer"><span>Para refletir</span><p>Separe um momento para meditar nesta Palavra e conversar com Deus em oração.</p></div></article></div></section>}<section className="section section-soft"><div className="container"><div className="section-heading split-heading"><div><p className="eyebrow">Mensagens semanais</p><h2>Devocionais anteriores</h2></div><p>Conteúdo breve, bíblico e simples de compartilhar.</p></div>{previous.length ? <div className="devotional-grid">{previous.map(item=><article key={item.id}><span>{formatDate(item.date)}</span><p>{item.subtitle}</p><h2>{item.title}</h2>{item.author && <strong>{item.author}</strong>}<p>{item.body}</p></article>)}</div> : <p className="public-empty">{featured ? "Os próximos devocionais aparecerão aqui sem repetir o destaque atual." : "Novos devocionais serão publicados em breve."}</p>}</div></section></main>; }
function formatDate(value:string){if(!value)return "";const [year,month,day]=value.split("-").map(Number);return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(year,month-1,day));}
