import type { Metadata } from "next";
export const metadata: Metadata = { title: "Nossa Igreja" };
export default function NossaIgrejaPage() { return <main>
  <section className="page-hero page-hero-church"><div className="container page-hero-inner"><p className="eyebrow eyebrow-light">Nossa igreja</p><h1>Uma história de fé,<br />pessoas e propósito.</h1><p>Conheça as convicções que nos movem e o coração que desejamos compartilhar com a cidade.</p></div></section>
  <section className="section story-section"><div className="container story-grid"><div className="sticky-heading"><p className="eyebrow">Nossa história</p><h2>Uma presença cristã em Guadalupe desde 1979.</h2></div><div className="story-copy"><p className="lead">A Primeira Igreja Batista Renovada em Guadalupe tem registro institucional desde 21 de fevereiro de 1979 e está localizada na Rua Fernando Lobo, 226.</p><p>O próprio nome expressa sua identidade completa e sua ligação com o bairro: não se trata de uma indicação separada de localização, mas da forma como a igreja é conhecida publicamente.</p><p>Sua profissão de fé pública apresenta a Bíblia como Palavra de Deus e regra de fé, Jesus Cristo como Salvador, a salvação pela graça mediante arrependimento e fé, além do batismo e da Ceia do Senhor como ordenanças da igreja.</p><div className="timeline"><div><strong>1979</strong><span>Registro institucional</span></div><div><strong>Guadalupe</strong><span>Raízes no bairro</span></div><div><strong>Hoje</strong><span>Fé, comunhão e serviço</span></div></div></div></div></section>
  <section className="section identity-section"><div className="container"><div className="section-heading centered-heading"><p className="eyebrow">Nossa identidade</p><h2>O que orienta cada passo.</h2></div><div className="identity-grid"><article><span>01</span><h3>Missão</h3><p>Conduzir pessoas a Jesus, formar discípulos e servir nossa cidade com amor prático.</p></article><article><span>02</span><h3>Visão</h3><p>Ser uma igreja saudável, relevante e multiplicadora, onde todas as gerações encontram lugar.</p></article><article><span>03</span><h3>Valores</h3><p>Graça, verdade, comunhão, generosidade, excelência, serviço e dependência de Deus.</p></article></div></div></section>
  <section className="section faith-section"><div className="container faith-grid"><div><p className="eyebrow eyebrow-light">Nossa fé</p><h2>Convicções firmes.<br />Corações acolhedores.</h2><p>Cremos nas verdades centrais da fé cristã e buscamos vivê-las com humildade, coerência e amor.</p></div><div className="faith-list">{[["A Bíblia", "É a Palavra de Deus e nossa referência de fé e prática."], ["Deus", "É único, eterno e revelado como Pai, Filho e Espírito Santo."], ["Jesus Cristo", "É o Filho de Deus, Salvador e centro de nossa esperança."], ["A salvação", "É presente da graça, recebido pela fé em Jesus."], ["A Igreja", "É uma família chamada a adorar, servir e compartilhar o evangelho."]].map(([title,text],index)=><article key={title}><span>0{index+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
  <section className="section pastor-section"><div className="container pastor-card"><div className="pastor-placeholder" role="img" aria-label="Símbolo da comunidade cristã"><span>PIBRG<br />Guadalupe</span></div><div><p className="eyebrow">Nossa comunidade</p><h2>Uma igreja ligada ao bairro.</h2><p className="pastor-role">Rua Fernando Lobo, 226 • Guadalupe</p><p>Acompanhe os canais oficiais para conhecer a liderança, os ministérios, as programações e os registros mais recentes da vida da igreja.</p><blockquote>“Existimos para o louvor e a glória do Senhor.”</blockquote><a className="text-link" href="https://www.instagram.com/pibrg/" target="_blank" rel="noreferrer">Conhecer a comunidade no Instagram <span>↗</span></a></div></div></section>
 </main>; }
