import type { Metadata } from "next";
import { getPublicContent } from "../../lib/site-content";
export const metadata: Metadata = { title: "Agenda" };
export const dynamic = "force-dynamic";
export default async function AgendaPage() { const events=await getPublicContent("event"); return <main>
  <section className="page-hero agenda-hero"><div className="container page-hero-inner"><p className="eyebrow eyebrow-light">Agenda</p><h1>Eventos, reuniões<br />e próximos passos.</h1><p>Uma área dinâmica para divulgar atividades, encontros, lançamentos e programações da organização.</p></div></section>
  <section className="section weekly-section"><div className="container"><div className="section-heading split-heading"><div><p className="eyebrow">Programação atual</p><h2>Próximos eventos</h2></div><p>A agenda pode ser atualizada diretamente pela equipe autorizada.</p></div>{events.length ? <div className="agenda-events public-agenda-events">{events.map(event=><article key={event.id}><div className="event-date-box"><strong>{event.date ? event.date.slice(8,10) : "—"}</strong><span>{event.date ? new Intl.DateTimeFormat("pt-BR",{month:"short",timeZone:"UTC"}).format(new Date(`${event.date}T00:00:00Z`)).replace(".","").toUpperCase() : "DATA"}</span></div><div><small>{event.subtitle}</small><h3>{event.title}</h3><span>{[event.time,event.location].filter(Boolean).join(" • ")}</span>{event.body && <p>{event.body}</p>}</div></article>)}</div> : <div className="agenda-events public-agenda-events"><article><div className="event-date-box"><strong>12</strong><span>SET</span></div><div><small>Evento demonstrativo</small><h3>Encontro com parceiros</h3><span>14:00 • Auditório principal</span><p>Exemplo de evento para demonstrar a apresentação da agenda.</p></div></article><article><div className="event-date-box"><strong>25</strong><span>SET</span></div><div><small>Conteúdo</small><h3>Workshop institucional</h3><span>09:00 • Online</span><p>Dados fictícios usados apenas na versão de portfólio.</p></div></article></div>}</div></section>
  <section className="section signup-section"><div className="container signup-grid"><div><p className="eyebrow eyebrow-light">Organização</p><h2>Mantenha todos informados</h2><p>Eventos podem incluir data, horário, local, categoria e descrição, com gerenciamento pela área administrativa.</p></div><div className="calendar-card"><div className="calendar-head"><strong>NEXA</strong><span>Agenda</span></div><p>Uma agenda institucional reduz informações espalhadas e cria um ponto único de consulta.</p><a className="button button-gold" href="/#contato">Fale conosco</a></div></div></section>
 </main>; }
