import type { Metadata } from "next";
import { getPublicContent } from "../../lib/site-content";
export const metadata: Metadata = { title: "Agenda" };
export const dynamic = "force-dynamic";
export default async function AgendaPage() { const events=await getPublicContent("event"); return <main>
  <section className="page-hero agenda-hero"><div className="container page-hero-inner"><p className="eyebrow eyebrow-light">Agenda</p><h1>Encontros que<br />fortalecem a caminhada.</h1><p>As programações da PIBRG são divulgadas pelos canais oficiais da igreja.</p></div></section>
  <section className="section weekly-section"><div className="container"><div className="section-heading split-heading"><div><p className="eyebrow">Programação atual</p><h2>Próximos encontros</h2></div><p>A agenda é atualizada pela secretaria da igreja.</p></div>{events.length ? <div className="agenda-events public-agenda-events">{events.map(event=><article key={event.id}><div className="event-date-box"><strong>{event.date ? event.date.slice(8,10) : "—"}</strong><span>{event.date ? new Intl.DateTimeFormat("pt-BR",{month:"short",timeZone:"UTC"}).format(new Date(`${event.date}T00:00:00Z`)).replace(".","").toUpperCase() : "DATA"}</span></div><div><small>{event.subtitle}</small><h3>{event.title}</h3><span>{[event.time,event.location].filter(Boolean).join(" • ")}</span>{event.body && <p>{event.body}</p>}</div></article>)}</div> : <p className="public-empty">Novas programações serão publicadas em breve.</p>}</div></section>
  <section className="section signup-section"><div className="container signup-grid"><div><p className="eyebrow eyebrow-light">Como chegar</p><h2>Visite a PIBRG</h2><p>Rua Fernando Lobo, 226<br />Guadalupe • Rio de Janeiro – RJ<br />CEP 21665-070</p></div><div className="calendar-card"><div className="calendar-head"><strong>PIBRG</strong><span>Guadalupe</span></div><p>Consulte a programação oficial e venha participar dos encontros da comunidade.</p><a className="button button-gold" href="https://www.google.com/maps/search/?api=1&query=Rua+Fernando+Lobo+226+Guadalupe+Rio+de+Janeiro" target="_blank" rel="noreferrer">Abrir no mapa</a></div></div></section>
 </main>; }
